require('settings')
require('mappings')
require('packer-config')
require('colorschemes-config.gruvbox')
require('statusbar')
require('mappings')
require('nvim-colorizer')

require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('telescope-config')
require('treesitter-config')
