require('settings')
require('mappings')
require('colorschemes-config.nightfox')
require('packer-config')
require('statusbar')
require('mappings')

require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('telescope-config')
